### PR TITLE
[RASTER LAYER: POINTS] use points over symbols for symbols of type 'c…

### PR DESCRIPTION
**Pull request by nytai**
…ircle'

# Merge Checklist
## :wrench: Issue(s) fixed:
- [ ] Author referenced issue(s) fixed by this PR:
- [ ] Fixes https://github.com/mapd/mapd-immerse/issues/3880

## :smoking: Smoke Test
- [ ] Works in chrome

## :ship: Merge
- [ ] author crafted PR's title into release-worthy commit message.

### CODE REVIEW

**Comment by nytai** [comment]
Testing instructions:

1. open up in local.
2. `npm start`
3. check that the scatter point example (example 4) works.
4. inspect vega call to see that is doesn't use symbols.

**Comment by micahstubbs** [comment]
will take a look now

**Comment by micahstubbs** [comment]
will test this example

screen shot 2018-02-12 at 2 24 46 pm

**Comment by micahstubbs** [comment]
it appears that this example is broken 🤔 

screen shot 2018-02-12 at 2 26 19 pm


```
Uncaught (in promise) TypeError: Cannot read property 'point' of undefined
    at Object._layer.__genVega (app.bundle.js:54870)
    at Object._layer._genVega (app.bundle.js:54942)
    at Object._layer.genVega (app.bundle.js:69144)
    at app.bundle.js:64348
    at Array.forEach (<anonymous>)
    at genLayeredVega (app.bundle.js:64347)
    at Object.<anonymous> (app.bundle.js:64064)
    at Object._chart.dataAsync (app.bundle.js:50748)
    at app.bundle.js:50800
    at new Promise (<anonymous>)
raster-chart.js:278 Uncaught TypeError: Cannot read property 'getCrossfilterId' of undefined
    at Object.<anonymous> (raster-chart.js:278)
    at Object._chart.data (base-mixin.js:309)
    at Object._chart._doRender (raster-chart.js:415)
    at Object._chart.render (base-mixin.js:806)
    at reSizeAll (example4.js:348)
    at e (lodash.js:10350)
    at a (lodash.js:10397)
    at f (lodash.js:10385)
(anonymous) @ raster-chart.js:278
_chart.data @ base-mixin.js:309
_chart._doRender @ raster-chart.js:415
_chart.render @ base-mixin.js:806
reSizeAll @ example4.js:348
e @ lodash.js:10350
a @ lodash.js:10397
f @ lodash.js:10385
raster-chart.js:278 Uncaught TypeError: Cannot read property 'getCrossfilterId' of undefined
    at Object.<anonymous> (raster-chart.js:278)
    at Object._chart.data (base-mixin.js:309)
    at Object._chart._doRender (raster-chart.js:415)
    at Object._chart.render (base-mixin.js:806)
    at reSizeAll (example4.js:348)
    at e (lodash.js:10350)
    at a (lodash.js:10397)
    at f (lodash.js:10385)
```

**Comment by micahstubbs** [comment]
see this error again after shutting down the examples server, installing node modules again, and then starting the examples server again 🤔

**Comment by micahstubbs** [comment]
ok, that fix works, can now see the example rendered 

screen shot 2018-02-12 at 3 14 57 pm

now to check the vega generated

**Comment by micahstubbs** [comment]
here's the vega spec that we send to mapd-core:

```
{
	"width": 728,
	"height": 241,
	"data": [
		{
			"name": "points",
			"sql":
				"SELECT goog_x as x, goog_y as y, followers as size, lang as color, tweets_nov_feb.rowid FROM tweets_nov_feb WHERE MOD(tweets_nov_feb.rowid * 265445761, 4294967296) < 3778891624 AND ((goog_x >= -19793718 AND goog_x <= 19926188) AND (goog_y >= -8000000 AND goog_y <= 8000000)) LIMIT 500000"
		}
	],
	"scales": [
		{
			"name": "x",
			"type": "linear",
			"domain": [-19793718, 19926188],
			"range": "width"
		},
		{
			"name": "y",
			"type": "linear",
			"domain": [-8000000, 8000000],
			"range": "height"
		},
		{
			"name": "points_size",
			"type": "linear",
			"domain": [0, 5000],
			"range": [1, 5],
			"clamp": true
		},
		{
			"name": "points_fillColor",
			"type": "ordinal",
			"domain": [
				"en",
				"pt",
				"es",
				"in",
				"und",
				"ja",
				"tr",
				"fr",
				"tl",
				"ru",
				"ar",
				"th",
				"it",
				"nl",
				"sv",
				"ht",
				"de",
				"et",
				"pl",
				"sl",
				"ko",
				"fi",
				"lv",
				"sk",
				"uk",
				"da",
				"zh",
				"ro",
				"no",
				"cy",
				"iw",
				"hu",
				"bg",
				"lt",
				"bs",
				"vi",
				"el",
				"is",
				"hi",
				"hr"
			],
			"range": [
				"rgba(39,174,239,1)",
				"rgba(234,85,69,1)",
				"rgba(135,188,69,1)",
				"rgba(179,61,198,1)",
				"rgba(244,106,155,1)",
				"rgba(237,225,91,1)",
				"rgba(189,207,50,1)",
				"rgba(239,155,32,1)",
				"rgba(77,182,172,1)",
				"rgba(237,191,51,1)",
				"rgba(124,77,255,1)"
			],
			"default": "rgba(39,174,239,1)",
			"nullValue": "rgba(202,202,202,1)"
		}
	],
	"marks": [
		{
			"type": "points",
			"from": { "data": "points" },
			"properties": {
				"x": { "scale": "x", "field": "x" },
				"y": { "scale": "y", "field": "y" },
				"fillColor": { "scale": "points_fillColor", "field": "color" },
				"size": { "scale": "points_size", "field": "size" }
			}
		}
	]
}
```

**Comment by micahstubbs** [comment]
from the Chrome dev tools network pane

screen shot 2018-02-12 at 3 20 25 pm

**Comment by micahstubbs** [comment]
ok, verified that this Vega spec doesn't use symbols ✅

**Pull request merged**
